### ISSUE TITLE
Initialisation fails when WroFilter is not of type ro.isdc.wro.http.WroFilter

### ISSUE THREAD

**Issue by tveimo** [lifus/wro4j-runtime-taglib#3]
Initialisation fails with error ...WroFilter is not registered in web.xml, if the WroFilter is not strictly an instance of ro.isdc.wro.http.WroFilter, eg instead being an instance of ro.isdc.wro.http.ConfigurableWroFilter.

**Comment by lifus** [comment]
Thanks for reporting this issue.
Filters assignable to [WroFilter](https://github.com/wro4j/wro4j/blob/1.7.x/wro4j-core/src/main/java/ro/isdc/wro/http/WroFilter.java) are now accepted by default.
