### ISSUE TITLE
Could TaglibContext be made non-final?

### ISSUE THREAD

**Issue by tveimo** [lifus/wro4j-runtime-taglib#5]
It would make it easier to change the initialisation if this class could be subclassed. Would imply making the constructor public as well.

**Comment by lifus** [comment]
TaglibContext is not designed for extension. I would rather use some DI framework than make TaglibContext non-final.
Anyway, what dependencies do you want to inject into TaglibContext? Is it connected to #2?

**Comment by tveimo** [comment]
Yes, #2. I currently need to call TaglibContext.initialize() since the tag classes uses TaglibContext and it can't be subclassed.

Did you get any further on https://github.com/wro4j/wro4j-runtime-taglib/issues/2#issuecomment-105159828 ? That would solve my issue I guess. 

I currently call TaglibContext.initialize() in my WroManagerFactory spring bean method, and have a locally patched ResourceUriCacheInitializer to use my local OptimizedResourcesRootProvider. 

I can't currently use the TaglibContextListener as it gets activated too early before spring has set everything up.

I can provide more details if you like.

**Comment by lifus** [comment]
> Did you get any further on [#2 (comment)](https://github.com/wro4j/wro4j-runtime-taglib/issues/2#issuecomment-105159828) ?

Yes, [It's](https://github.com/wro4j/wro4j-runtime-taglib/commit/5697c36a8e38912c1cf2a0c33d8ab84019b7ab04) already on master branch. I updated [README](https://github.com/wro4j/wro4j-runtime-taglib#optimizedresourcesrootstrategy) accordingly. Patching shouldn't be required anymore for the future versions. If it works for you, I would probably release v0.2.0 sometime soon.

**Comment by tveimo** [comment]
Yes this works very well!

**Comment by lifus** [comment]
Great, I'm closing this one for now then.
