### ISSUE TITLE
Feature request: optional domain attribute to tag, or as a configuration parameter

### ISSUE THREAD

**Issue by tveimo** [lifus/wro4j-runtime-taglib#8]
We use a CDN for our production environment, so I add a hostname prefix to resources for the production Spring environment profile. I think an optional hostname could either be added as an attribute to the script and style taglib, or through the wro.properties file.

Alternatively, there could be a third tag that merely provides the path / url to the resource with the correct fingeprint, if needed eg for use in Javascript. The CDN hostname could then be prefixed manually.

**Comment by lifus** [comment]
I'm not sure that I understand but it seems to me that [built-in wro4j model interpolation](https://code.google.com/p/wro4j/wiki/WroModelInterpolation) might be exactly what you are looking for.

**Comment by tveimo** [comment]
That one would allow me to prefix included resources in a group to load them from different places, but what I need is to have output from the Script/StylesheetTag like

``` html
<script src='//keycdn-14576.keycdn.com/resources/core-52b380f59cd70730bccbf2da93a87595.js'>  
</script>
```

if I use the script tag like 

``` html
<c:set var="cdn" value="//keycdn-14576.keycdn.com" />
<!-- spring profile dependent -->
<wro:script group="core" prefix="${cdn}" />
```

**Comment by lifus** [comment]
Does it make sense to make it application-wide or you need a more fine-grained control over your resources?
e.g. I might support something like

``` ini
resourceDomain=//keycdn-14576.keycdn.com
```

in wro.properties. This would affect all resources though

**Comment by tveimo** [comment]
This would be sufficient in my case, since we load all css/js resources from the cdn.

**Comment by lifus** [comment]
Alright, changes are on resourceDomain branch. Tests are green but I didn't have a chance to test it on actual CDN so I would keep it there for a while.

**Comment by tveimo** [comment]
Ok, it works well, if configured in the wro.properties file. However, when configuring through spring, wro.properties might be loaded from elsewhere, eg. if using a different wro.properties file depending on the deployment profile. 

See eg. https://groups.google.com/forum/#!msg/wro4j/GUQ9zmDDVbw/E0VzlrC7dEUJ

I'm not sure what's the best approach here. Would it be possible to retrieve the configuration properties from the wroManagerFactory?

**Comment by lifus** [comment]
You might override ConfigurableWroManagerFactory#newConfigProperties.
e.g. you may store common properties in wro.properties and put all environment-specific properties in wro-{environment}.properties. Then you might load them based on current spring environment profile

**Comment by tveimo** [comment]
True, but I still can't override resourceDomain only for the production environment, since it's loaded using ServletContextPropertyWroConfigurationFactory which fetches the wro.properties file from a hardcoded location.

**Comment by lifus** [comment]
Right, I forgot that there is no such thing as single source of properties in wro4j.
I should probably introduce something like Wro4jManagerFactory to taglib.
In the mean time, you might fallback to [something like this](http://git.beesli.cz/users/michal.repasek/repos/jablopoint/browse/andel-web/build.xml?at=c07e18b#21).

**Comment by tveimo** [comment]
Ok, I might use a workaround for now. The current setup I've got is pretty good at the moment.

**Comment by lifus** [comment]
Closing this one for now as I'm going to include current implementation in 0.2.0 release. Feel free to reopen it
