### ISSUE TITLE
hash not updating when css content changes

### ISSUE THREAD

**Issue by tveimo** [lifus/wro4j-runtime-taglib#9]
I'm not sure if it's an error in my configuration, or a bug, but it seems that a webapp restart is required for the hash of a group to update. 

Eg. I can update a less file, and see it's content change when i reload the resulting css for that particular group, using the same resource name / hash. If I restart the webapp, then I get an exception, eg.

ro.isdc.wro.WroRuntimeException: No such group available in the model: external-d3a9f9523f74c740f8a9daaa03412331

I didn't realize this until I got my cache headers set up properly, so I didn't see that the group hash didn't change when the content changed until now. Here's my current configuration;

gzipResources=true
minimizeEnabled=true
ignoreMissingResources=false
jmxEnabled=true
hashStrategy=MD5
namingStrategy=hashEncoder
cacheUpdatePeriod=18000
modelUpdatePeriod=18000

optimizedResourcesRootStrategy=predefined
optimizedResourcesRoot=/resources/wro/

preProcessors=less4j,cssUrlRewriting,lessCssImport,semicolonAppender
postProcessors=cssMinJawr,jsMin
uriLocators=servletContext,uri,classpath

I've tried both the master branch and the resourceDomain branch.

**Comment by lifus** [comment]
> it seems that a webapp restart is required for the hash of a group to update.

You may use [resourceWatcherUpdatePeriod](https://code.google.com/p/wro4j/wiki/ConfigurationOption) during development. I thought I've mentioned it in [README file](https://github.com/wro4j/wro4j-runtime-taglib#features)
Note: Please make sure to turn it off in production.

> If I restart the webapp, then I get an exception, eg.
> ro.isdc.wro.WroRuntimeException: No such group available in the model: external-d3a9f9523f74c740f8a9daaa03412331

Default wro4j in-memory cache gets invalidates after restart. It shouldn't be an issue because taglib generates relevant resource url and inserts it in resulting html.
You shouldn't rely on hashed name. If you really want to get the latest version of resource directly(e.g. from code) you should use it's raw unhashed url e.g. external.css

**Comment by tveimo** [comment]
Ok, it wasn't configured in this example, but I've tried a lot of different combinations. Am now thinking that something is preventing the scheduler from running so that the cache isn't invalidated when a file changes. I might try to debug a bit in wro4j-core to see what is going on.

**Comment by tveimo** [comment]
Just to clarify if I've understood the intended way this should work;

Whenever a resource changes, wro:script /wro:stylesheet should produce markup & url with a different resource fingerprint/hash than before the resource changed, without a server restart?

**Comment by tveimo** [comment]
It might be that my understanding of how the resourceWatcher thread works was wrong, it doesn't appear to actually monitor any files directly. If I reload a js/css group manually in the browser then on the next run of a wro4j-runtime-tag i a JSP, it will use an updated hash.

**Comment by lifus** [comment]
> Whenever a resource changes, wro:script /wro:stylesheet should produce markup & url with a different resource fingerprint/hash than before the resource changed, without a server restart?

Exactly, given that value of resourceWatcherUpdatePeriod is not zero

**Comment by lifus** [comment]
Closing this one as well. I hope you are not experiencing this issue anymore, feel free to reopen it otherwise
